初回表示で画像のキャッシュが残ってセルがチラつくことがある
uhooi/UhooiPicBook pull request #131
Opened 2020-11-13 08:34 UTC by crane-hiromu

PR投げときます笑

１回表示されると画像がキャッシュされて高速化されるので再現できない、ので再インストールして高速スクロールするとみれるはず〜

2020-11-13 09:11 UTC, uhooi commented
これずっと気になっていたんだけど、セルが再利用されてキャッシュを持っちゃっていたのか！
公式ドキュメントに `prepareForReuse()` の使い方も書いてあって、まさに `UICollectionViewCell` をデフォルト値にするために呼ぶメソッドのよう。

気になる点をいくつかコメントしたらマージさせていただきます 🙏 

ref:

- https://developer.apple.com/documentation/uikit/uicollectionreusableview/1620141-prepareforreuse
- https://qiita.com/takehilo/items/1145240bb3b72f7d0317

2020-11-13 09:19 UTC, uhooi requested changes

2020-11-13 09:19 UTC, uhooi commented on UhooiPicBook/Modules/MonsterList/Views/MonsterCollectionViewCell.swift
> +
```suggestion

```

2020-11-13 09:19 UTC, uhooi commented on UhooiPicBook/Modules/MonsterList/Views/MonsterCollectionViewCell.swift
> +
```suggestion

```

2020-11-13 09:19 UTC, uhooi commented on UhooiPicBook/Modules/MonsterList/Views/MonsterCollectionViewCell.swift
> +        iconImageView.image = nil
個人的な好みだけど、プロパティのアクセスは常に `self.` を付けてほしいです 🙏 

```suggestion
        self.iconImageView.image = nil
```

2020-11-13 09:19 UTC, uhooi commented on UhooiPicBook/Modules/MonsterList/Views/MonsterCollectionViewCell.swift
> +        iconImageView.image = nil
名前ラベルも同様に `self.nameLabel.text = nil` で初期化したほうがよさそうだけど、どうなんだろ？
名前が再利用されるときもある気がした！

2020-11-13 09:20 UTC, uhooi commented on UhooiPicBook/Modules/MonsterList/Views/MonsterCollectionViewCell.swift
> +
SwiftLintの指摘をなるべくなくしたいので 🙇

2020-11-13 09:20 UTC, uhooi commented on UhooiPicBook/Modules/MonsterList/Views/MonsterCollectionViewCell.swift
> +
上記と同様です 🙇

2020-11-14 02:03 UTC, uhooi commented
@crane-hiromu いくつかコメントしたので、暇なときに確認お願いします〜 🙏

2020-11-14 03:56 UTC, crane-hiromu commented on UhooiPicBook/Modules/MonsterList/Views/MonsterCollectionViewCell.swift
> +        iconImageView.image = nil
stringは高速だからやらなくてもぶっちゃけ大丈夫だけど、一応入れておきますか！

2020-11-14 04:46 UTC, uhooi commented on UhooiPicBook/Modules/MonsterList/Views/MonsterCollectionViewCell.swift
> +        iconImageView.image = nil
なるほど画像は高速じゃないからってことか！
でもこれでOKです 👌

2020-11-14 04:47 UTC, merged

2020-11-14 04:47 UTC, uhooi commented
LGTM :)