キャラクター選択可能なウィジェットを追加
uhooi/UhooiPicBook pull request #140
Opened 2020-11-28 08:03 UTC by Koshimizu-Takehito

## 概要

キャラクター選択可能な small ウィジェットを試しに追加してみました。
好みあると思いますので、そっとクローズしていただいてもOKです👍 
 
既存 small, medium ウィジェットのように時間でキャラクターを更新しつつ、キャラクターを選択する機能は実装していません。
「ウィジェットを編集」の選択値をプログラムから指定できなそうなことが理由で諦めました。

## やったこと

### 実装内容

- [Making a Configurable Widget](https://developer.apple.com/documentation/widgetkit/making-a-configurable-widget) にしたがって実装
    - SiriKit intent definition を追加
    - Intent Handler を追加
    - Intent Timeline Provider を実装

### プロジェクト構成（概要）

UhooiPicBookWidgetsConfigurableIntent ターゲットを新規追加

```bash
.
├── UhooiPicBookWidgets
│    └── Monster
│        └── MonsterConfigurableWidget.swift        # Configurable Widget / Intent Timeline Provider
└── UhooiPicBookWidgetsConfigurableIntent
     ├── IntentDefinition                           # Intent Definition / Intents files
     └── IntentHandler.swift                        # Intent Handler
```

## スクリーンショット

### ウィジェットの追加

| 新規の small を追加 |
| ---- |
| <img src="https://user-images.githubusercontent.com/30564669/100495885-05ab5480-3193-11eb-96db-4238d8f61c99.PNG" width="180"/> |

### ウィジェットの編集

1.選択前 | 2.編集 | 3.一覧表示 | 4.選択後
---- | ---- | ---- | ----
<img src="https://user-images.githubusercontent.com/30564669/100495700-6c2f7300-3191-11eb-8b18-6bd6754b5aaf.jpg" width="180"/> | <img src="https://user-images.githubusercontent.com/30564669/100495701-6e91cd00-3191-11eb-9264-51fcf5685d5d.jpg" width="180"/> | <img src="https://user-images.githubusercontent.com/30564669/100495702-6f2a6380-3191-11eb-80c3-03d251ea1eb4.jpg" width="180"/> | <img src="https://user-images.githubusercontent.com/30564669/100495703-6fc2fa00-3191-11eb-8139-f2aa4a6d3db0.jpg" width="180"/>

2020-11-29 08:14 UTC, uhooi commented
@Koshimizu-Takehito PRありがとうございますー！
私の実装漏れで申し訳ないのですが、 `UhooiPicBookWidgets` フォルダがSwiftLintの適用外になっていたので、 `develop` ブランチを取り込んでプッシュしていただけると助かります 🙇 
SwiftLintの警告は、直しづらかったらそのままでも大丈夫です！

2020-11-29 10:09 UTC, Koshimizu-Takehito commented
@uhooi 了解です！対応しますー！

2020-11-29 10:27 UTC, Koshimizu-Takehito commented
@uhooi 
cecde4b で develop をマージしました。今回の実装範囲内では Lint 警告なしでした 👍 
c47e27c で SwiftLint の適用範囲を追加しました。
よろしくお願いしますー！

2020-12-02 01:16 UTC, uhooi commented
ご対応ありがとうございます 🙏 
レビューはウィジェットについて勉強しつつ行いたいため、もう少しかかりそうです 🙇

2020-12-02 04:05 UTC, Koshimizu-Takehito commented
承知しましたー！
勉強教材として、この PR を使っちゃってください ☺️

2020-12-06 14:23 UTC, uhooi requested changes

2020-12-06 14:23 UTC, uhooi commented on project.yml
> +      - UhooiPicBookWidgetsConfigurableIntent/IntentDefinition
こちらは問題なさそうなので修正不要ですが、XcodeGenでプロジェクトを生成すると、なぜか `IntentDefinition` フォルダが `UhooiPicBookWidgetsConfigurableIntent` フォルダの外に出てしまいます。

![スクリーンショット 2020-12-06 23 07 18](https://user-images.githubusercontent.com/21194714/101282329-eb6b1980-3817-11eb-8708-63ca2ba41f8e.png)

2020-12-06 14:23 UTC, uhooi commented on UhooiPicBookWidgetsConfigurableIntent/Info.plist
> +	<string>1.0</string>
こちらは警告が発生していませんが、他のターゲットとバージョンを統一していただきたいです 🙏 

```suggestion
	<string>$(MARKETING_VERSION)</string>
```

2020-12-06 14:23 UTC, uhooi commented on UhooiPicBookWidgetsConfigurableIntent/Info.plist
> +	<string>1</string>
以下の警告が発生しているため、他のターゲットとバージョンを統一していただきたいです 🙏

> warning: The CFBundleVersion of an app extension ('1') must match that of its containing parent app ('14').

```suggestion
	<string>$(CURRENT_PROJECT_VERSION)</string>
```

2020-12-06 14:24 UTC, uhooi commented
まだウィジェットの勉強不足でレビュー中ですが、取り急ぎ気になる箇所だけコメントしました！
デバッグして動作は問題なさそうでした、好きなキャラクターを選べるの最高過ぎる…笑

2020-12-07 01:18 UTC, Koshimizu-Takehito commented on project.yml
> +      - UhooiPicBookWidgetsConfigurableIntent/IntentDefinition
63c53a2 で Shared の下に移動してみました。いかがでしょう？

<img width="300" alt="スクリーンショット 2020-12-07 10 14 01" src="https://user-images.githubusercontent.com/30564669/101299303-159ef480-3875-11eb-989b-8ac4c35c1c4c.png">

<img width="300" alt="スクリーンショット 2020-12-07 10 14 14" src="https://user-images.githubusercontent.com/30564669/101299316-27809780-3875-11eb-857f-dbf11991bc04.png">

2020-12-08 05:44 UTC, uhooi commented on project.yml
> +      - UhooiPicBookWidgetsConfigurableIntent/IntentDefinition
あ… `IntentDefinition` フォルダ内のファイルは `UhooiPicBookWidgetsConfigurableIntent` ターゲットのみで使われるため、そのままのほうがありがたかったです、、
他に `Shared` を使うターゲットを追加したときに `excludes` するのを忘れそうなので、、

2020-12-08 06:25 UTC, uhooi commented on project.yml
> +      - UhooiPicBookWidgetsConfigurableIntent/IntentDefinition
いや、公式ドキュメントに以下の記載があったので、製品ターゲットにも `IntentDefinition` を含めるのが正しそうですね 🤔 

> __Important__
> 
> In the File inspector, verify that the containing app, the widget extension, and the intent extension all include the intent definition file.

現状だとTarget Membershipで製品ターゲットのチェックがOFFになっているので、ONにして、 `excludes` しないよう修正するのがよさそうです。
<img width="265" alt="スクリーンショット 2020-12-08 15 21 54" src="https://user-images.githubusercontent.com/21194714/101447766-35174980-3969-11eb-8173-aecdb5c3523f.png">

パスはSharedの下のままで問題ありません！

2020-12-08 07:05 UTC, Koshimizu-Takehito commented on project.yml
> +      - UhooiPicBookWidgetsConfigurableIntent/IntentDefinition
> 他に Shared を使うターゲットを追加したときに excludes するのを忘れそうなので

これは、ご指摘の通りでなんですよねー（ ちょっと気になっていました ）
今後ターゲット増えた際に、intentdefinition を使わずに、Shared を利用したいターゲットとか普通にありえそうなので、Shared の配下はイマイチかもしれないですね。（Shared は基本的に excludes しない方針ですよね？）

2020-12-08 07:49 UTC, Koshimizu-Takehito commented on project.yml
> +      - UhooiPicBookWidgetsConfigurableIntent/IntentDefinition
取れる選択肢はこんなところでしょうか。

- パスはSharedの配下のまま（ excludes はやめる  ）
- IntentDefinitionフォルダをトップレベルで作成、必要なターゲットに追加

2020-12-08 10:02 UTC, uhooi requested changes

2020-12-08 10:02 UTC, uhooi commented on UhooiPicBookWidgetsConfigurableIntent/IntentHandler.swift
> +
難しい処理をかんたんにさせていただきました 🙏 

```suggestion
        self.repository.loadMonsters { result in
            switch result {
            case let .success(monsters):
                let inMonsters = monsters
                    .sorted { $0.order < $1.order }
                    .map(INMonster.init)
                completion(INObjectCollection(items: inMonsters), nil)
```

2020-12-08 10:02 UTC, uhooi commented on project.yml
> +          -  "IntentDefinition/**"
製品ターゲットにも `IntentDefinition` は必要とのことなので、除外は不要です。

```suggestion
      - Shared
```

2020-12-08 10:06 UTC, uhooi commented on project.yml
> +      - UhooiPicBookWidgetsConfigurableIntent/IntentDefinition
`Shared` の具体的な方針までは考えていませんでしたが、以下を想定していました。

- 2つ以上のターゲットで使われるファイルをすべて格納する
- excludesせず、必要なもののみsourcesに書く

対応としては、ひとまず `パスはSharedの配下のまま（ excludes はやめる ）` でお願いします 🙏

2020-12-08 10:12 UTC, uhooi commented on Shared/IntentDefinition/Base.lproj/WidgetsConfiguration.intentdefinition
> +					<string>INMonster</string>
[質問]
インテントで定義するタイプに `IN` のプリフィックスを付けるのは一般的なのでしょうか？

2020-12-08 10:12 UTC, uhooi commented
@Koshimizu-Takehito 
レビューが完了しました！
コメントが多くて恐縮ですが、よろしくお願いします 🙇

2020-12-08 11:06 UTC, Koshimizu-Takehito commented on Shared/IntentDefinition/Base.lproj/WidgetsConfiguration.intentdefinition
> +					<string>INMonster</string>
ここもちょっと悩んだところなんですよね。指摘が鋭いw

何も考えずに `Monster` としたいところなのですが、万が一、他のフレームワークでも `Monster` という名前を使いたい場合が発生した際に命名を考え直さないといけないと思いまして。

たとえば、CoreData とか Realm でオブジェクトを永続化したい要求が発生した場合です。
そのフレームワークに依存した同じような Monster クラスを作成することになるので、名前の衝突が発生するかもしれないと考えました。

とはいえ、Module を分割することで名前衝突を回避することはできるので、将来上記のような要求が発生した際に Module 分割する想定で、`INMonster` はやめて、単純に `Monster` にしてしまっても良いかもしれないです。

2020-12-08 11:08 UTC, Koshimizu-Takehito commented
@uhooi 
丁寧にフィードバックしていただきありがとうございます ☺️ 
時間を見つけて諸々修正いたします 🙏

2020-12-08 11:09 UTC, Koshimizu-Takehito commented on project.yml
> +      - UhooiPicBookWidgetsConfigurableIntent/IntentDefinition
> ひとまず パスはSharedの配下のまま（ excludes はやめる ） でお願いします

承知しましたー！

2020-12-08 15:08 UTC, uhooi commented on Shared/IntentDefinition/Base.lproj/WidgetsConfiguration.intentdefinition
> +					<string>INMonster</string>
あ、私も `Monster` は避けたいと思っています。
そのために `MonsterDTO` や `MonsterEntity` などの構造体ができてしまっていますが、、ｗ

単に `IN` のプリフィックスがよく使われるのか気になりました！
`Monster` に変えるならこのままで問題ありません。

2020-12-08 15:10 UTC, uhooi commented on project.yml
> +      - UhooiPicBookWidgetsConfigurableIntent/IntentDefinition
`project.yml` でコメントしたので、こちらは解決とします。

2020-12-08 15:20 UTC, uhooi commented on UhooiPicBookWidgetsConfigurableIntent/IntentHandler.swift
> +    override func handler(for intent: INIntent) -> Any { self }
[質問]
こちらをオーバーライドしているのにはどのような意味があるのでしょうか？
`handler(for:)` メソッドを理解しておらず… 🙇

2020-12-08 23:41 UTC, Koshimizu-Takehito commented on UhooiPicBookWidgetsConfigurableIntent/IntentHandler.swift
> +    override func handler(for intent: INIntent) -> Any { self }
すみません、不要な実装みたいですので削除いたします 🙏 
デフォルトで `self` を返しているみたいです。

---

`INIntent` の型をチェックして、自身のクラスでは制御することができない場合に、他のクラスに処理を転送する目的で利用するみたいです。

```swift
override func handler(for intent: INIntent) -> Any? {        
    switch intent {
    case is INSendMessageIntent:
        return SendMessageHandler()
    case is INSearchForMessagesIntent:
        return SearchForMessagesHandler()
    default:
        return nil
    }
}
```

[**handler(for:) | Apple Developer Documentation**](https://developer.apple.com/documentation/sirikit/inintenthandlerproviding/1638898-handler)

---

Info.plist で IntentsSupported を `SelectMonsterIntent` しか対応しないように設定していますので、このような分岐も不要でOKだと思いました。

2020-12-08 23:50 UTC, Koshimizu-Takehito commented on Shared/IntentDefinition/Base.lproj/WidgetsConfiguration.intentdefinition
> +					<string>INMonster</string>
> 単に IN のプリフィックスがよく使われるのか気になりました！

よく使われるかというとちょっとわからないですね。。

プロジェクト的に `...DTO` や `...Entity` としているので、サフィックスで判断できるように揃えても良いと思いました。
そうすると、INObject のサブタイプなので、**MonsterIntentObject** とかになりそうです。

- INMonster のままでいく
- ~Monster にする~
- MonsterIntentObject にする（ サフィックスでどこの所属か分かるようにする ）

2020-12-08 23:52 UTC, Koshimizu-Takehito commented
修正ひきつづきやっていきます！終わりましたらメンション飛ばしますので、よろしくお願いします！

2020-12-09 12:08 UTC, uhooi commented on UhooiPicBookWidgetsConfigurableIntent/IntentHandler.swift
> +    override func handler(for intent: INIntent) -> Any { self }
詳細なご説明ありがとうございますー！
では解決にします。

2020-12-09 12:12 UTC, uhooi commented on Shared/IntentDefinition/Base.lproj/WidgetsConfiguration.intentdefinition
> +					<string>INMonster</string>
それでしたら `MonsterIntentObject にする（ サフィックスでどこの所属か分かるようにする ）` でお願いします！

2020-12-10 00:56 UTC, uhooi commented on Shared/IntentDefinition/INMonster+extra.swift
> +//  INMonster.swift
ご対応ありがとうございます！

2020-12-10 00:58 UTC, uhooi commented on UhooiPicBookWidgets/Monster/MonsterConfigurableWidget.swift
> +    typealias Intent = ConfigurationIntent
ご対応ありがとうございます！

2020-12-10 00:59 UTC, uhooi commented on UhooiPicBookWidgetsConfigurableIntent/Info.plist
> +				<string>ConfigurationIntent</string>
ご対応ありがとうございます！

2020-12-10 01:00 UTC, uhooi commented on Shared/IntentDefinition/Base.lproj/WidgetsConfiguration.intentdefinition
> +			<string>Configuration</string>
ご対応ありがとうございます！

2020-12-10 01:01 UTC, uhooi commented on UhooiPicBookWidgetsConfigurableIntent/IntentHandler.swift
> +final class IntentHandler: INExtension, ConfigurationIntentHandling {
ご対応ありがとうございます！

2020-12-10 01:03 UTC, uhooi commented on UhooiPicBookWidgets/Monster/MonsterConfigurableWidget.swift
> +
ご対応ありがとうございます！

2020-12-10 01:06 UTC, uhooi commented on UhooiPicBookWidgets/Monster/MonsterConfigurableWidget.swift
> +            kind: Self.kind,
https://github.com/uhooi/UhooiPicBook/pull/140/commits/80dfece1f587702af6e0fdf2bff65a5567be3dac
こちらの修正ですが、構造体名などと分けた理由はありますか？
`kind` の命名方法は統一したいので、 `MonsterWidget` と同じく構造体名から末尾の `Widget` を取った文字列にしていただきたいです 🙏

2020-12-10 01:21 UTC, uhooi commented on Shared/IntentDefinition/Base.lproj/WidgetsConfiguration.intentdefinition
> +			<string>Configuration</string>
ご対応ありがとうございます！

2020-12-12 07:48 UTC, Koshimizu-Takehito commented on UhooiPicBookWidgets/Monster/MonsterConfigurableWidget.swift
> +                completion(try? result.get())
了解です！実装を揃えますー！

2020-12-12 08:06 UTC, Koshimizu-Takehito commented on Shared/IntentDefinition/Base.lproj/WidgetsConfiguration.intentdefinition
> +					<string>INMonster</string>
対応しました！

2020-12-12 08:07 UTC, Koshimizu-Takehito commented on UhooiPicBookWidgetsConfigurableIntent/IntentHandler.swift
> +        for intent: ConfigurationIntent,
対応しました！

2020-12-12 08:09 UTC, Koshimizu-Takehito commented on UhooiPicBookWidgets/Monster/MonsterConfigurableWidget.swift
> +            kind: Self.kind,
了解ですー！

2020-12-12 08:10 UTC, Koshimizu-Takehito commented on UhooiPicBookWidgets/Monster/MonsterConfigurableWidget.swift
> +            kind: Self.kind,
修正しました！

2020-12-12 08:26 UTC, Koshimizu-Takehito commented on UhooiPicBookWidgets/Monster/MonsterConfigurableWidget.swift
> +        }
指摘ありがとうございます！
自分の理解が足りていなかったです。固定で良さそうです。
修正します！

2020-12-12 08:27 UTC, Koshimizu-Takehito commented on UhooiPicBookWidgets/Monster/MonsterConfigurableWidget.swift
> +        }
修正しました！

2020-12-12 08:28 UTC, Koshimizu-Takehito commented on Shared/IntentDefinition/Base.lproj/WidgetsConfiguration.intentdefinition
> +					<string>Body</string>
修正しました！

2020-12-12 08:31 UTC, Koshimizu-Takehito commented on Shared/IntentDefinition/ja.lproj/WidgetsConfiguration.strings
> +"SVmOax" = "順番";
修正しました！

2020-12-12 08:31 UTC, Koshimizu-Takehito commented on Shared/IntentDefinition/ja.lproj/WidgetsConfiguration.strings
> +"LDC0ih" = "アイコン URL";
修正しました！

2020-12-12 08:31 UTC, Koshimizu-Takehito commented on Shared/IntentDefinition/ja.lproj/WidgetsConfiguration.strings
> +"mlnQMc" = "ダンス URL";
修正しました！

2020-12-12 08:31 UTC, Koshimizu-Takehito commented on Shared/IntentDefinition/INMonster+extra.swift
> +//  UhooiPicBookSelectIntent
修正しました！

2020-12-12 08:32 UTC, Koshimizu-Takehito commented on Shared/IntentDefinition/INMonster+extra.swift
> +            let order = order
お！これは知らなかったです！ありがとうございます 😄 
修正します！

2020-12-12 08:34 UTC, Koshimizu-Takehito commented on Shared/IntentDefinition/INMonster+extra.swift
> +}
削除しました！

2020-12-12 08:36 UTC, Koshimizu-Takehito commented on Shared/IntentDefinition/en.lproj/WidgetsConfiguration.strings
> +"4VaDj8" = "Configuration";
これは自動生成ですね（ 現在のコミットでは Configuration ではなく SelectMonster ）
ユーザに表示されることはなさそうなので、削除して問題がなければ削除してみます。

2020-12-12 08:48 UTC, Koshimizu-Takehito commented on Shared/IntentDefinition/en.lproj/WidgetsConfiguration.strings
> +"4VaDj8" = "Configuration";
問題無さそうでしたので、削除しました。

2020-12-12 08:57 UTC, Koshimizu-Takehito commented
@uhooi 修正終わりました。ご確認よろしくお願いします 🙏

2020-12-12 12:31 UTC, uhooi commented on UhooiPicBookWidgets/Monster/MonsterConfigurableWidget.swift
> +            kind: Self.kind,
確認しました、ありがとうございますー！

2020-12-12 12:31 UTC, uhooi commented on UhooiPicBookWidgets/Monster/MonsterConfigurableWidget.swift
> +        }
確認しました、ありがとうございますー！

2020-12-12 12:31 UTC, uhooi commented on Shared/IntentDefinition/Base.lproj/WidgetsConfiguration.intentdefinition
> +					<string>Body</string>
確認しました、ありがとうございますー！

2020-12-12 12:31 UTC, uhooi commented on Shared/IntentDefinition/ja.lproj/WidgetsConfiguration.strings
> +"SVmOax" = "順番";
確認しました、ありがとうございますー！

2020-12-12 12:31 UTC, uhooi commented on Shared/IntentDefinition/ja.lproj/WidgetsConfiguration.strings
> +"LDC0ih" = "アイコン URL";
確認しました、ありがとうございますー！

2020-12-12 12:34 UTC, uhooi commented on Shared/IntentDefinition/en.lproj/WidgetsConfiguration.strings
> +"4VaDj8" = "Configuration";
https://github.com/uhooi/UhooiPicBook/pull/140/commits/532ee2cca14a9cc4e6f82cb2cc147742550a15b8
あ、自動生成でしたら削除しないほうがいいと思います… 🙏

2020-12-12 12:35 UTC, uhooi commented on Shared/IntentDefinition/ja.lproj/WidgetsConfiguration.strings
> +"mlnQMc" = "ダンス URL";
確認しました、ありがとうございますー！

2020-12-12 12:35 UTC, uhooi commented on UhooiPicBookWidgetsConfigurableIntent/IntentHandler.swift
> +        for intent: ConfigurationIntent,
確認しました、ありがとうございますー！

2020-12-12 12:35 UTC, uhooi commented on Shared/IntentDefinition/Base.lproj/WidgetsConfiguration.intentdefinition
> +					<string>INMonster</string>
確認しました、ありがとうございますー！

2020-12-12 12:38 UTC, uhooi commented on Shared/IntentDefinition/MonsterIntentObject+Convert.swift
> +//  MonsterIntentObjectr+Convert.swift
細かいですがtypoです。

```suggestion
//  MonsterIntentObject+Convert.swift
```

2020-12-12 12:39 UTC, uhooi commented on UhooiPicBook/Resources/Info.plist
> +	</array>
[質問]
こちらを追加された理由は何でしょうか？
https://github.com/uhooi/UhooiPicBook/pull/140/commits/b39a5662650e8f1c411efb50cf4288008a6c390b

2020-12-12 12:43 UTC, uhooi commented on Shared/IntentDefinition/INMonster+extra.swift
> +//  UhooiPicBookSelectIntent
修正されていない気がします…ご確認お願いしますm(_ _)m

2020-12-12 12:43 UTC, uhooi commented on Shared/IntentDefinition/INMonster+extra.swift
> +            let order = order
ご修正ありがとうございますー！

2020-12-12 12:44 UTC, uhooi commented on Shared/IntentDefinition/INMonster+extra.swift
> +}
確認しました、ありがとうございますー！

2020-12-12 12:45 UTC, uhooi commented
@Koshimizu-Takehito 
ご修正ありがとうございます…！
いくつかコメントしたのでご確認お願いします（何度もすみません、、）。

2020-12-13 02:56 UTC, Koshimizu-Takehito commented on Shared/IntentDefinition/MonsterIntentObject+Convert.swift
> +//  MonsterIntentObjectr+Convert.swift
修正しました 🙇

2020-12-13 02:59 UTC, Koshimizu-Takehito commented on UhooiPicBook/Resources/Info.plist
> +	</array>
WidgetsConfiguration.intentdefinition を App のターゲットに追加したタイミングで自動で追加されたものになります。
（ これは無くても特に困らないかも思いつつ、追加を尊重しました ）

2020-12-13 03:01 UTC, Koshimizu-Takehito commented on Shared/IntentDefinition/en.lproj/WidgetsConfiguration.strings
> +"4VaDj8" = "Configuration";
了解しました。自動生成を尊重しますね。

2020-12-13 03:02 UTC, Koshimizu-Takehito commented on Shared/IntentDefinition/en.lproj/WidgetsConfiguration.strings
> +"4VaDj8" = "Configuration";
10afbd1 で戻しました。

2020-12-13 03:04 UTC, Koshimizu-Takehito commented on Shared/IntentDefinition/INMonster+extra.swift
> +//  UhooiPicBookSelectIntent
03aaed7 で修正しました 🙏

2020-12-13 03:07 UTC, Koshimizu-Takehito commented
@uhooi 何度も見ていただいてありがとうございます！！ 🙇 
修正とコメント返信しましたので、ご確認よろしくお願いします。

2020-12-14 02:18 UTC, uhooi commented on UhooiPicBook/Resources/Info.plist
> +	</array>
自動追加でしたらOKです！！！

2020-12-14 02:20 UTC, uhooi commented on Shared/IntentDefinition/en.lproj/WidgetsConfiguration.strings
> +"4VaDj8" = "Configuration";
ありがとうございますー！

2020-12-14 02:21 UTC, uhooi commented on Shared/IntentDefinition/INMonster+extra.swift
> +//  UhooiPicBookSelectIntent
ありがとうございますー！

2020-12-14 02:23 UTC, uhooi commented
LGTMです 👍 
本当にありがとうございました！！！

2020-12-14 02:23 UTC, merged

2020-12-14 03:51 UTC, Koshimizu-Takehito commented
レビューありがとうございましたー！